refactor of graph.h and rewriter.h on types and functions names
olympic-minds/testlib pull request #10
Opened 2024-07-21 22:31 UTC by JakubPiotrowicz

2024-07-21 22:33 UTC, JakubPiotrowicz commented
We should discuss moving Graph creation functions from readwriter.h to gaph.h

2024-07-22 19:58 UTC, dominikstrak2001 commented on gen-utils.hpp
rename to graph_utils.hpp

2024-07-22 19:59 UTC, dominikstrak2001 commented on gen-utils.hpp
> +#ifndef READWRITER_H_
:eyes:

2024-07-22 20:05 UTC, dominikstrak2001 approved these changes
seems sane

2024-07-22 20:06 UTC, dominikstrak2001 requested changes
rename gen utils

2024-07-22 22:20 UTC, dominikstrak2001 approved these changes

2024-07-22 22:23 UTC, merged